/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 upgradeddog-v1.glb --transform 
Files: upgradeddog-v1.glb [46.42KB] > C:\Users\salih\OneDrive\Masaüstü\vscode\testing, attention pls!\goingbananas\public\upgradeddog-v1-transformed.glb [5.23KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/upgradeddog-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.dogmodel.geometry} material={materials.skin} scale={0.06} />
    </group>
  )
}

useGLTF.preload('/upgradeddog-v1-transformed.glb')
